name 'helloworld'
maintainer 'The Authors name'
maintainer_email 'test@example.com'
license 'all_rights'
description 'Installs/Configures helloworld'
long_description 'Installs/Configures helloworld'
version '0.1.0'
